# Generated by Django 4.0.3 on 2022-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emns', '0003_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_series',
            field=models.CharField(choices=[('Cisco Router 3725 Series', 'Cisco Router 3725 Series'), ('Cisco Router 7200 Series', 'Cisco Router 7200 Series'), ('Cisco Router 7600 Series', 'Cisco Router 7600 Series'), ('Cisco Catalyst 2960 Series', 'Cisco Catalyst 2960 Series'), ('Cisco Catalyst 3850 Series', 'Cisco Catalyst 3850 Series'), ('Juniper Router ACX7100 Series', 'Juniper Router ACX7100 Series'), ('Juniper Router J6350 Series', 'Juniper Router J6350 Series'), ('Juniper Switch EX Series', 'Juniper Switch EX Series'), ('MikroTik Router CCR1036 Series', 'MikroTik Router CCR1036 Series'), ('MikroTik Router CCR2004 Series', 'MikroTik Router CCR2004 Series'), ('MikroTik Switch CRS310 Series', 'MikroTik Switch CRS310 Series')], max_length=255),
        ),
    ]
